# Generated by Django 5.2.8 on 2025-11-17 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Electronics', 'Electronics'), ('Clothing', 'Clothing'), ('Books', 'Books'), ('Home', 'Home')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('inventoryStatus', models.CharField(choices=[('INSTOCK', 'In Stock'), ('LOWSTOCK', 'Low Stock'), ('OUTOFSTOCK', 'Out of Stock')], max_length=20)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('image', models.CharField(max_length=100)),
            ],
        ),
    ]
